import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />

        <link href="/assets/css/bootstrap-icons.css" rel="stylesheet" />

        <link rel="stylesheet" href="/assets/css/swiper-bundle.min.css" />

        <link rel="stylesheet" href="/assets/css/nice-select.css" />

        <link rel="stylesheet" href="/assets/css/animate.min.css" />
        <link rel="stylesheet" href="/assets/css/jquery.fancybox.min.css" />

        <link href="/assets/css/boxicons.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="/assets/css/style.css" />
      </head>
      <body className={inter.className}>{children}</body>

    </html>
  );
}
